---

- name: Ensure Drush is installed globally via Composer.
  composer:
    command: require
    global_command: yes
    arguments: "drush/drush:{{ drush_version }}"
  register: drush_composer_require
  # Set environment variable
  environment:
    COMPOSER_HOME: /usr/local/composer

- name: Update global Drush install if configured.
  composer:
    command: update
    global_command: yes
    arguments: "drush/drush --with-dependencies"
  when:
    - drush_keep_updated
    - not drush_composer_require.changed
  environment:
      COMPOSER_HOME: /usr/local/composer

- name: Ensure globally-installed Drush is symlinked into bin dir.
  file:
    src: "/usr/local/composer/vendor/bin/drush"
    dest: "{{ drush_path }}"
    state: link

- name: Run drush to finish setting it up
  command: "{{ drush_path }}"
  register: drush_result
  changed_when: "'Execute a drush command' not in drush_result.stdout"
  become: no
