---

- name: Clone Drush from GitHub
  git:
    repo: https://github.com/drush-ops/drush.git
    dest: "{{ drush_install_path }}"
    version: "{{ drush_version }}"
    update: "{{ drush_keep_updated }}"
    force: "{{ drush_force_update }}"
  register: drush_clone

- name: Check for composer.json
  stat: path={{ drush_install_path }}/composer.json
  register: drush_composer

- name: Install Drush & dependencies with Composer at {{ drush_install_path }}
  composer:
    command: "install"
    arguments: "{{ drush_composer_cli_options }}"
    working_dir: "{{ drush_install_path }}"

- name: Create drush symlink at {{ drush_path }}
  file:
    src: "{{ drush_install_path }}/drush"
    dest: "{{ drush_path }}"
    state: link

- name: Run drush to finish setting it up
  command: "{{ drush_path }}"
  register: drush_result
  changed_when: "'Execute a drush command' not in drush_result.stdout"
  become: no
